version: 0.0
containers:
    LambdaFunctions:
        phases:
            install:
                commands:
                    - npm install
                    - npm install -g serverless
            build:
                commands:
                    - serverless deploy --stage cicd | tee deploy.out
