version: 0.0
containers:
    LambdaFunctions:
        phases:
            install:
                commands:
                    - apt update
                    - apt install -y npm
                    - npm install
                    - npm install -g serverless
            build:
                commands:
                    - serverless package
